/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as langchain_db from "../langchain/db.js";
import type * as _add_add from "../_add/add.js";
import type * as _create_load from "../_create/load.js";
import type * as _readAll_readAll from "../_readAll/readAll.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "langchain/db": typeof langchain_db;
  "_add/add": typeof _add_add;
  "_create/load": typeof _create_load;
  "_readAll/readAll": typeof _readAll_readAll;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
