import type { Metadata } from 'next';
import Navigation from '@/components/Navigation';
import Provider from '@/components/Provider';
import Modal from '@/components/Modal';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="w-full h-full flex grow mt-16 bg-stone-950 ">
      <div className="h-full w-full flex px-8 pt-10">
        <Provider>
          <Navigation />
          <div className="h-full px-9  w-full">{children}</div>
          <Modal />
        </Provider>
      </div>
    </main>
  );
}
